language: rust
rust: nightly
sudo: false

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
      after_success:
        - travis-cargo doc-upload
    - os: osx
      env: TARGET=x86_64-apple-darwin NO_ADD=1
    - os: osx
      env: TARGET=i686-apple-darwin
    - env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
      install: pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script: cargo doc
      after_success:
        - travis-cargo --only nightly doc-upload

script:
  - if [ -z "$NO_ADD" ]; then rustup target add $TARGET; fi
  - cargo run --target $TARGET --manifest-path systest/Cargo.toml
  - cargo build --target $TARGET
  - cargo build --target $TARGET --features profiling
  - cargo build --target $TARGET --features debug
  - cargo build --target $TARGET --features 'debug profiling'
  - cargo test --target $TARGET
env:
  global:
    - secure: "2Z1z4ir++XEQb9eegYTMolsNfTo1aATric2k4KfvRgnG1nAvvccf1Jg0828PVeqqD6w5f+X52AVT4bTDXbSL5L+/cTiBuVmY3943nyNOgHxFBTbVlnLtGnh18bb7AQAhyH1L9KjiLptMtFUfIg3TQ9r0QS+cBEJMFiE8BuuQMq/uPZYF3QMuV8W+9AwnqZPgdZV4q7LRnx2gHyVKifRfa4v0TxJA+fY5euON8CKemw12yVTZyNS5WUq6GLvQa5KsSYOSAIYizxz8Mze8plQytc6VhF3OuFyJ72u5LAx+szyxIu8zNAkyNeUqI1/V1gnlhWbZfov6KV56qoV9U8+xKp1J/nCXdabHEO/saOgWk4XgSSc7JNsT1PMPKT18r7JwNha0DS2onWBbegYMV0YXyH/WVAM+oXvhZAj7WPz5bHRbgkatGmBZD2jOjRQxzSugJsZzsmrKbWm8lIoyJGdNxTn5CisYElZvP1CV1OFaQBkaLfmnlpbJ0NQXpQdnpgXuLvI7sXptyn0Bjt41JQclB2BU98SrEiR0hPlkh8m4fH/QpQ8WdXEtvKXTX8UtG5RPW0UvTZVZtrU4Weyu2Hctj2D/hkXywtBXp7mUhB21fBGiaEc+vh6Q2OrZPrwoAj3YWfLlNBjFmfKmUwXXLno4FLLUujFmmypgs4Qit5HtzwQ="
notifications:
  email:
    on_success: never
